# Test Raffia passed settings

# ---
# SLAM_TASKNAME: Debug settings passed without facts
# SLAM_Q: [ triage, play ]
# ---

---
- hosts: "{{ NODE }}"
  gather_facts: false
  tasks:
    - debug: var=ansible_winrm_server_cert_validation
