---
- debug: var=ansible_host

- name: Success
  raw: exit 0

- name: Fail
  raw: exit 1
  ignore_errors: yes

- name: Skipped
  raw: exit 0
  when: true == false

- name: Partial Skipped
  raw: exit 0
  when: ansible_host | search("[13579]$")

- name: Partial Success
  raw: >
    {{ (ansible_host | search("[13579]$")) | ternary('exit 0', 'exit 1') }}
  ignore_errors: yes

- name: Partial Success with skipped
  raw: >
    {{ (ansible_host | search("[13579]$")) | ternary('exit 0', 'exit 1') }}
  ignore_errors: yes
  when: ansible_host | search("[013-9]$")

- name: This task deliberately has a veeeeeeeeeeeeeeeeeeery looooooooooooooooooooooooong task name to force ellipsis clipping in diagram
  raw: exit 0

- name: Fail with stderr (linux)
  raw: 'echo "stderr goes here" >&2; exit 1'
  ignore_errors: yes
  when: ansible_system == 'Linux'

- name: Fail with stdout (linux)
  raw: 'echo "stdout goes here"; exit 1'
  ignore_errors: yes
  when: ansible_system == 'Linux'

- name: Fail with stderr & stdout (linux)
  raw: 'echo "stderr goes here" >&2; echo "stdout goes here"; exit 1'
  ignore_errors: yes
  when: ansible_system == 'Linux'

#- name: Fail with stderr (windows)
#  raw: >
#    Write-Error "stderr goes here"
#    exit 1
#  ignore_errors: yes
#  when: ansible_os_family == 'Windows'
#
#- name: Fail with stdout (windows)
#  raw: 'echo "stdout goes here"; exit 1'
#  ignore_errors: yes
#  when: ansible_os_family == 'Windows'
#
#- name: Fail with stderr & stdout (windows)
#  raw: 'echo "stderr goes here" >&2; echo "stdout goes here"; exit 1'
#  ignore_errors: yes
#  when: ansible_os_family == 'Windows'
